plugins:
  - jekyll-relative-links
theme: minimal
relative_links:
  enabled: true
  collections: true
include:
  - index.md

title: "Ecosia: the board game"
description: "The sustainable game that teaches about reforesting"