plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
relative_links:
  enabled: true
  collections: true
include:
  - index.md

title: "Ecosia: the board game"
description: "The sustainable game that teaches about reforesting"
logo: "img/boardgamelogo.svg"